// <auto-generated />
using System;
using CTU_Recruits.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CTU_Recruits.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CTU_Recruits.Models.Employer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CompanyName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Employer");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CompanyName = "Techer",
                            Description = "jfkdlsahjkdasghsdjka",
                            Name = "Mary"
                        },
                        new
                        {
                            Id = 2,
                            CompanyName = "ITD",
                            Description = "jfkdlsahjkdasghsdjka",
                            Name = "John"
                        },
                        new
                        {
                            Id = 3,
                            CompanyName = "UMC",
                            Description = "jfkdlsahjkdasghsdjka",
                            Name = "Sam"
                        });
                });

            modelBuilder.Entity("CTU_Recruits.Models.JobSeeker", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CVPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<string>("PhotoPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PublicCV")
                        .HasColumnType("bit");

                    b.Property<string>("Skills")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("YearsOfExperience")
                        .IsRequired()
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("JobSeeker");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CVPath = "~/Images/CV.png",
                            Description = "jkfld;ajskgl;ag",
                            Name = "Mary",
                            PhotoPath = "~/Images/Mary.jpg",
                            PublicCV = true,
                            Skills = "abc",
                            YearsOfExperience = 1
                        },
                        new
                        {
                            Id = 2,
                            CVPath = "~/Images/CV.png",
                            Description = "jkfld;ajskgl;ag",
                            Name = "John",
                            PhotoPath = "~/Images/John.jpg",
                            PublicCV = true,
                            Skills = "def",
                            YearsOfExperience = 1
                        },
                        new
                        {
                            Id = 3,
                            CVPath = "~/Images/CV.png",
                            Description = "jkfld;ajskgl;ag",
                            Name = "Sam",
                            PhotoPath = "~/Images/Sam.jpg",
                            PublicCV = true,
                            Skills = "ghi",
                            YearsOfExperience = 1
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
